export const ARTICLES_ACTION_TYPES = {
    FETCH_ARTICLES_START: 'articles/FETCH_ARTICLES_START',
    FETCH_ARTICLES_SUCCESS: 'articles/FETCH_ARTICLES_SUCCESS',
    FETCH_ARTICLES_FAILED: 'articles/FETCH_ARTICLES_FAILED',
    UPDATE_ARTICLES_START: 'articles/UPDATE_ARTICLES_START',
    UPDATE_ARTICLES_SUCCESS: 'articles/UPDATE_ARTICLES_SUCCESS',
    UPDATE_ARTICLES_FAILED: 'articles/UPDATE_ARTICLES_FAILED',
    ARTICLE_CLICKS_START: 'articles/ARTICLE_CLICKS_START',
    ARTICLE_CLICKS_SUCCESS: 'articles/ARTICLE_CLICKS_SUCCESS',
    ARTICLE_CLICKS_FAILED: 'articles/ARTICLE_CLICKS_FAILED'
}