export const REVIEWS_ACTION_TYPES = {
    FETCH_REVIEWS_ON_ARTICLE_START: 'reviews/FETCH_REVIEWS_ON_ARTICLE_START',
    FETCH_REVIEWS_ON_ARTICLE_SUCCESS: 'reviews/FETCH_REVIEWS_ON_ARTICLE_SUCCESS',
    FETCH_REVIEWS_ON_ARTICLE_FAILED: 'reviews/FETCH_REVIEWS_ON_ARTICLE_FAILED',
    CREATE_REVIEWS_ON_ARTICLE_START: 'reviews/CREATE_REVIEWS_ON_ARTICLE_START',
    CREATE_REVIEWS_ON_ARTICLE_SUCCESS: 'reviews/CREATE_REVIEWS_ON_ARTICLE_SUCCESS',
    CREATE_REVIEWS_ON_ARTICLE_FAILED: 'reviews/CREATE_REVIEWS_ON_ARTICLE_FAILED',
    REVIEW_THUMBSUPS_START: 'reviews/THUMBSUPS_START',

    REVIEW_COMMENT_START: 'reviews/COMMENT_START',
    UPDATE_REVIEW_START: 'UPDATE_REVIEW_START',
    UPDATE_REVIEW_SUCCESS: 'UPDATE_REVIEW_SUCCESS',
    UPDATE_REVIEW_FAILED: 'UPDATE_REVIEW_FAILED',
    GET_ALLREVIEWS_START: 'reviews/GET_ALLREVIEWS_START',
    GET_ALLREVIEWS_SUCCESS: 'reviews/GET_ALLREVIEWS_SUCCESS',
    GET_ALLREVIEWS_FAILED: 'reviews/GET_ALLREVIEWS_FAILED',
}